baseURL = "https://simoncoudeville.be/"
languageCode = "en-us"
title = "Simon Coudeville"
theme = "Coudeville"
relativeURLS = false
canonifyurls = true
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[params]
  author = "Simon Coudeville"
  description = "Personal website of Simon Coudeville"
