baseURL = "https://simoncoudeville.be/"
languageCode = "en-us"
title = "Simon Coudeville"
theme = "coudeville"
relativeURLS = false
canonifyurls = true
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  author = "Simon Coudeville"
  description = "Tesla's Awesome Hugo Site"
